global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h
  receiver: 'Telegram'
  
  routes:
  - match:
      severity: critical
    receiver: Telegram
    group_by: [alertname, instance]  # только эти labels

receivers:
  - name: 'Telegram'
    telegram_configs:
      - bot_token: 'TOKEN'
        chat_id: -100123
        send_resolved: true


templates:
  - '/etc/alertmanager/*.tmpl'