global:
  scrape_interval: 5s
  external_labels:
    site: prod

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'airflow'
    static_configs:
      - targets: ['statsd-exporter:9102']
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']